[package]
name = "api-linter"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1"
clap = { version = "3", features = ["derive"] }
rustdoc-types = "0.6"
smithy-rs-tool-common = { version = "0.1", path = "../smithy-rs-tool-common" }
serde_json = "1"
